# (generated by chatgpt)

# Specify the directory you want to add to the PATH
$directoryToAdd = Join-Path $PSScriptRoot "commands"

# Get the current PATH environment variable
$currentPath = [System.Environment]::GetEnvironmentVariable("Path", [System.EnvironmentVariableTarget]::Machine)

# Check if the directory is already in the PATH
if ($currentPath -split ";" -notcontains $directoryToAdd) {
    # If it's not in the PATH, add it
    $newPath = $currentPath + ";" + $directoryToAdd
    [System.Environment]::SetEnvironmentVariable("Path", $newPath, [System.EnvironmentVariableTarget]::Machine)
    Write-Host "Directory added to the PATH. Please restart your terminal for changes to take effect."
} else {
    Write-Host "Directory is already in the PATH."
}